### ISSUE TITLE
work without console?

### ISSUE THREAD

**Issue by wenzowski** [benchristel/ji#4]
Just in case you haven't already seen this, [error-stack-parser](https://github.com/stacktracejs/error-stack-parser/blob/master/error-stack-parser.js) is only 209 sloc and gets you cross-browser stack frames wherever available (IE10+).

**Comment by benchristel** [comment]
I'm not sure how error-stack-parser would obviate the need for the console--does it work with `eval`d code?

Actually, my reason for printing test failures to the console is that I like the Chrome console's way of printing deep object structures. Eventually, I want the `toEqual` matcher to do deep comparison of objects and arrays, which means the failure message would have to print those structures somehow. IMO it's nice (if a bit hacky) to just truncate nested structures in the banner message and print them to the console, where the user can use the dev tools they're already familiar with to navigate them.

**Comment by wenzowski** [comment]
Why, [yes indeed](https://github.com/stacktracejs/stackframe/issues/8) `eval`d code is fine.

I use [not-so-shallow](https://github.com/sotojuan/not-so-shallow/blob/master/index.js) all over the place, though it sounds like you're going to write your own. I like the Chrome way too–it's disappointing to get stuck in a browser with a more spartan console. And that's where this half-baked thought came from.

There's chrome style pretty printing in [redux-devtools-log-monitor](https://github.com/gaearon/redux-devtools-log-monitor), though that depends on all the stuffs.

**Comment by wenzowski** [comment]
Hmm. So diffing deep object structures is non-trivial because javascript objects can have circular references, and those can't be serialized to json. Didn't think through how difficult this would be. Console it is. Closing.

A pretty json diff from another project.

``` javascript
import chalk from 'chalk';
import * as JsDiff from 'diff';

export function prettyDiff(actual, expected) {
  const diff = JsDiff.diffJson(expected, actual).map(part => {
    if (part.added) return chalk.green(part.value.replace(/.+/g, '    - $&'));
    if (part.removed) return chalk.red(part.value.replace(/.+/g, '    + $&'));
    return chalk.gray(part.value.replace(/.+/g, '    | $&'));
  }).join('');
  return `\n${diff}\n`;
}
```
